### ISSUE TITLE
[Question] Зависимости от Docker и Selenoid

### ISSUE THREAD

**Issue by fojetin** [Black-Triangle-code/Telegram_coin_bot#4]
@Black-Triangle-code 
В [README.md](https://github.com/Black-Triangle-code/Telegram_coin_bot/blob/master/README.md) написано, что проект каким-то образом зависит от Docker, Selenoid.
Я удалил (закоментировал) `RunChromeTests`, остановил Selenoid и проект прекрасно работает без него, потребляет меньше ресурсов.

Зачем нужен Selenoid в v2? Может эти зависимости остались от старой версии бота?

**Comment by Black-Triangle-code** [comment]
Не все задания одинаковы и не все задания решаются простым reqwest для выполнения некоторых необходимо открыть сайт в браузере, в активной вкладке, убедится что там нет капчи и проигрывать определенный java скрипт в течении определенного времени. Эти задания редко но бывают, именно для выполнения их подцеплен Selenoid

**Comment by matvey-istomin** [comment]
А вот и нет. Все задания можно решать, посылая http запросы, так что это docker и selenoid - это ненужные вещи, которые к тому же потребляют ресурсы.

**Comment by fojetin** [comment]
@Black-Triangle-code 
> Не все задания одинаковы и не все задания решаются простым reqwest для выполнения некоторых необходимо открыть сайт в браузере, в активной вкладке, убедится что там нет капчи и проигрывать определенный java скрипт в течении определенного времени. Эти задания редко но бывают, именно для выполнения их подцеплен Selenoid

Да, я слышал это в видео.
Дело в том, что в существующей версии проекта Selenoid никак не используется! Просто нет такого кода.

**Comment by fojetin** [comment]
> У меня получилось сделать более красивое и лучшее решение.

Залей пожалуйста)

**Comment by Black-Triangle-code** [comment]
> @ Black-треугольник-код
> 
> > Не все задания одинаковы и не все задания решаются простым reqwest для выполнения некоторых необходимо открыть сайт в браузере, в активной вкладке, убедится что там нет капчи и проигрывать определенный java скрипт в течении определенного времени. Эти задания редко но бывают, именно для выполнения их подцеплен Selenoid
> 
> Да, я слышал это в видео.
> Дело в том, что в существующей версии проекта Selenoid никак не используется! Просто нет такого кода.

Ну как это не используется)) мы скармливаем ссылку сервису селеноид что запущен на локалхосте на порту 4444

Я не спорю что можно использовать и другие способы, но в данном случае и докер и селеноид используются и нужны и не являются растратой ресурсов как вы ошибочно пологаете

**Comment by matvey-istomin** [comment]
Что тогда лучше: модуль requests + beautifulsoup4 или докер + selenoid? Вы совершаете over engineering. Они тут явно лишние

**Comment by fojetin** [comment]
@Black-Triangle-code 
> Ну как это не используется)) мы скармливаем ссылку сервису селеноид что запущен на локалхосте на порту 4444

Окей, я не слишком хорошо разбираюсь в работе с Selenoid.
Подскажите пожалуйста, какой именно кусок кода отвечает за скармливание ссылки в селеноид?
